apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dp
  namespace: wanderlust
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-dp
  template:
    metadata:
      labels:
        app: backend-dp
    spec:
      containers:
      - name: backend
        image: keshav0503/wanderlust-backend:1.2
        ports:
        - containerPort: 3000
