apiVersion: v1
kind: Service
metadata:
  name: wanderlust-frontend
spec:
  selector:
    app: wanderlust-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 
