apiVersion: v1
kind: Service
metadata:
  name: wanderlust-frontend
spec:
  selector:
    app: wanderlust-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: ClusterIP
